CREATE DATABASE AGENDA;

USE AGENDA;

CREATE TABLE GRUPO(
	CODGRUPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(300) NOT NULL DEFAULT ''
);

CREATE TABLE CONTATO(
	CODCONTATO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	CODGRUPO INT NOT NULL,
    NOME VARCHAR(1000) NOT NULL DEFAULT '',
    TELEFONE VARCHAR(50) NOT NULL DEFAULT '',
    CELULAR VARCHAR(50) NOT NULL DEFAULT '',    
    CONSTRAINT FK_GRUPO_CONTATO FOREIGN KEY(CODGRUPO)
							REFERENCES GRUPO(CODGRUPO)
);