DROP DATABASE IF EXISTS CONTATO;

CREATE DATABASE IF NOT EXISTS CONTATO;

USE CONTATO;

CREATE TABLE IF NOT EXISTS CONTATO(
	CODCONTATO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(500) NULL,    
	EMAIL VARCHAR(150) NOT NULL,
    TELEFONE VARCHAR(30) NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPO(
	CODGRUPO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(150) NOT NULL
);

CREATE TABLE IF NOT EXISTS GRUPOCONTATO(
	CODGRUPOCONTATO INT NOT NULL PRIMARY KEY AUTO_INCREMENT,

	CODGRUPO INT NOT NULL,
    CONSTRAINT FK_GRUPO_GRUPOCONTATO 
		FOREIGN KEY (CODGRUPO) 
		REFERENCES GRUPO(CODGRUPO),
         
	CODCONTATO INT NOT NULL,
	CONSTRAINT FK_CONTATO_GRUPOCONTATO 
		FOREIGN KEY(CODCONTATO) 
        REFERENCES CONTATO(CODCONTATO)                      
);













