CREATE DATABASE IF NOT EXISTS controlecomissao;

USE controlecomissao;

CREATE TABLE IF NOT EXISTS VENDEDOR(
	CODVENDEDOR INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(500) NOT NULL,
    ENDERECO VARCHAR(300) NOT NULL,
	CPF VARCHAR(14) NOT NULL
);

CREATE TABLE IF NOT EXISTS COMISSAO(
	CODCOMISSAO INT NOT NULL PRIMARY KEY,
    CODVENDEDOR INT NOT NULL,
    DATACOMISSAO DATE NOT NULL,
    VALOR DOUBLE PRECISION NOT NULL,
	CONSTRAINT FK_VENDEDOR_COMISSAO
		FOREIGN KEY(CODVENDEDOR)
        REFERENCES VENDEDOR(CODVENDEDOR)
);

INSERT INTO VENDEDOR
	VALUES (1, 'João', 'Rua Marechal', '123456789-00')