CREATE DATABASE IF NOT EXISTS CONTATO;

USE CONTATO;

CREATE TABLE IF NOT EXISTS CONTATO(
	CODCONTATO INT PRIMARY KEY,
    NOME VARCHAR(500),    
	EMAIL VARCHAR(150),
    TELEFONE VARCHAR(30)
);

CREATE TABLE IF NOT EXISTS GRUPO(
	CODGRUPO INT PRIMARY KEY,
    NOME VARCHAR(150)
);

CREATE TABLE IF NOT EXISTS GRUPOCONTATO(
	CODGRUPOCONTATO INT PRIMARY KEY,
    CODGRUPO INT,
    CODCONTATO INT,
    /*Definindo os relacionamentos entre
    as tabelas*/
    CONSTRAINT FK_GRUPO_GC FOREIGN KEY 
         (CODGRUPO) REFERENCES GRUPO(CODGRUPO),
	CONSTRAINT FK_CONTATO_GC FOREIGN KEY
		 (CODCONTATO) REFERENCES CONTATO(CODCONTATO)                      
);













